# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

target 'CLAMap3DExmaple' do
    
#    pod 'AMap3DMap'
    pod 'CLUIKit'

end
